FROM kristoferb/spbase_ros2:galactic

ARG project_name=robotiq_2f_driver

# install any deps here and clone any external repos into the workspace
COPY ./robotiq_2f_msgs/ /ws/src/robotiq_2f_msgs

# Copy the packages and only the rust package and cargo files to build the rust deps.
COPY ./$project_name/Cargo.* \
    ./$project_name/package.xml \
    ./$project_name/r2r_cargo.cmake \
    ./$project_name/CMakeLists.txt \
    /ws/src/$project_name/
RUN . /opt/ros/$ROS_DISTRO/setup.sh &&\
    cd /ws &&\
    mkdir ./src/$project_name/src/ &&\
    echo "fn main() {}" > ./src/$project_name/src/main.rs &&\
    colcon build

RUN rm -r /ws/src/$project_name/src/

RUN sed --in-place --expression \
    '$isource "/ws/install/setup.bash"' \
    /entrypoint.sh
RUN echo '. /entrypoint.sh' >> ~/.bashrc 
